# -*- coding: utf-8 -*-
"""ex1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AUSLzkI3L-Vu07qTrIIxisIXcafUWiTn
"""

#Função que calcula a área de um triângulo qualquer
#Com o conhecimento da base e da altura:
  #A função multiplica base e altura e divide por 2.
    #Se a área for maior do que 10, imprime na tela ("maior")
    #Se a área for meno ou igual a 10, imprime na tela ("menor ou igual")

def area_tri(base,altura):
  areatri = (base * altura) / 2

  if areatri > 10 :
    print ("maior")
  else:
    print ("menor ou igual")