# -*- coding: utf-8 -*-
"""ex0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sMstYTu9guO6jRV2FanniwyKCuh0jmBO
"""

#A função faz a soma das variáveis n1 à n4 com seus respectivos pesos e divide pelo total de variáveis, no caso 10.
#Retornando o resultado da média ponderada

def media_ponderada(n1,n2,n3,n4): 
  return (n1 + n2 + 3 * n3 + 5 * n4) / 10