# -*- coding: utf-8 -*-
"""ex2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aSD2u1cnKnDx0gYczQfjDUn96rx1mhvE
"""

#Define a lista
#Verifica se o "seu_nusp" está nesta lista:
  #1. Se estiver, retorna sim
  #2. Se não estiver, retorna não

lista_nusp = [91235, 46782, 12345, 42149, 794, 18362, 82016, 11, 5932, 1818, 91375, 246,
1920, 1820, 29, 4823, 2540, 18, 28342, 81230, 92304, 9213, 289, 23819, 98233]

def encontra_nusp(seu_nusp,lista_nusp):
 if seu_nusp in lista_nusp:
    print("sim")
 else:
   print("nao")

encontra_nusp(82016, lista_nusp)