# -*- coding: utf-8 -*-
"""ex4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k_zfN1sDDu8nvRmlS6tu9FFNnjR8IKQx
"""

#Define o multiplicador inicial como 1 para não atrapalhar na multiplicação inicial
#while limita as multiplicações até 10
#If define a primeira multiplicação como o primeiro resultado a ser somado
#Nas outras iterações do laço o resultado da multiplicação será somado ao resultado das multiplicações anteriores que também foram somadas
#No final do laço aumenta em 1 o multiplicador para seguir aumentando as multiplicações até 10

def soma_tabuada(n):
  multiplicador = 1
  while multiplicador <= 10 :
   multiplicacao = n * multiplicador 
   if multiplicador == 1:
     resultado_soma = multiplicacao
   else:
     resultado_soma = multiplicacao + resultado_soma 
   multiplicador += 1
  print(resultado_soma)