# -*- coding: utf-8 -*-
"""ex5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yVhiG_iIs2HZrbWHNjcWrLOCg15ibVnT
"""

#A função começa definindo a variavel soma como zero para nao interferir no inicio.
#O laço while realiza operações de divisão inteira por 10 para atualizar o número dado a cada repetição tirando um algorismo
#O laço while só para quando a divisão inteira por 10 dar zero, porque quer dizer que é o último algorismo
#As somas são realizadas com o resto da divisão de n por 10 e o resto da divisão de n por 10 do laço anterior
  #A o resto da divisão n por 10 nos dá o último algorismo do número do input 
  #O n divido inteiramente por 10 reduz o número do input em um algorismo
#Quando no último algorismo a divisão por 10 resulta zero finalizando o laço while.
#Dando o resultado para o úsuario na tela.

def soma_digitos(n):
  soma = 0 
  while n > 0:
   soma = n % 10 + soma
   n = n // 10
  print(soma)